In [1]:
import pandas
from sklearn.linear_model import LinearRegression, ElasticNet, SGDRegressor, BayesianRidge
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
# from catboost import CatBoostRegressor
from sklearn.kernel_ridge import KernelRidge
# from xgboost.sklearn import XGBRegressor
# from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score

In [2]:
all_data=pandas.read_csv("Training Dataset.csv")
all_data

Condition No. 1  Condition No. 2  Condition No. 3  Condition No. 4  \
0                3687.5           4510.6           9.3160           26.734   
1                3685.5           4511.5           9.3103           26.661   
2                3682.8           4570.5           9.2759           26.653   
3                3573.8           4547.2           9.3265           26.517   
4                3644.3           4530.7           9.3318           27.119   
...                 ...              ...              ...              ...   
150264           3602.0           4488.5           9.2903           26.737   
150265           3658.9           4541.8           9.4212           26.887   
150266           3664.7           4481.6           9.3381           27.136   
150267           3716.2           4502.5           9.4016           26.967   
150268           3716.2           4502.5           9.4016           26.967   

        Condition No. 5  Condition No. 6  Condition No. 7  Condition No. 8  \
0                42.511           74.935           120.42          0.33407   
1                42.478           75.888           120.41          0.32859   
2                42.224           75.779           120.43          0.35016   
3                42.246           74.906           120.38          0.33413   
4                42.199           75.036           120.42          0.34601   
...                 ...              ...              ...              ...   
150264           42.304           74.364           120.39          0.33959   
150265           42.675           76.042           120.42          0.34050   
150266           41.835           74.236           120.42          0.31717   
150267           41.867           74.662           120.43          0.34990   
150268           41.867           74.662           120.43          0.34990   

        Condition No. 9  Condition No. 10  ...  Condition No. 25  \
0                80.345            24.203  ...            4.9187   
1                79.935            26.669  ...            4.7347   
2                80.379            23.216  ...            4.8275   
3                80.407            25.154  ...            4.8399   
4                80.233            24.941  ...            4.8477   
...                 ...               ...  ...               ...   
150264           80.119            25.181  ...            4.8674   
150265           79.780            23.205  ...            4.8172   
150266           80.462            23.216  ...            4.8518   
150267           80.211            25.184  ...            4.7766   
150268           80.211            25.184  ...            4.7766   

        Condition No. 26  Condition No. 27  Condition No. 28  \
0                 2.3120          0.018975           0.84982   
1                 2.2965          0.021290           0.85223   
2                 2.2578          0.015472           0.81907   
3                 2.3040          0.007096           0.84621   
4                 2.2572          0.023564           0.83298   
...                  ...               ...               ...   
150264            2.3276          0.010042           0.88338   
150265            2.2964          0.038459           0.81802   
150266            2.2640         -0.002473           0.82219   
150267            2.3251          0.018484           0.81109   
150268            2.3251          0.018484           0.81109   

        Condition No. 29  Condition No. 37  Condition No. 35  \
0               0.107870            53.729            43.107   
1               0.119180            54.179            45.041   
2               0.098032            54.413            42.933   
3               0.101700            53.603            44.186   
4               0.097448            52.915            43.488   
...                  ...               ...               ...   
150264          0.095266            53.332            43.710   
150265          0.087961            

In [3]:
x=all_data.drop(columns=['Targetted Condition No. 1'])
y=all_data['Targetted Condition No. 1']
y

0         3098.8
1         3113.9
2         3100.0
3         3102.7
4         3107.4
           ...  
150264    3108.0
150265    3116.9
150266    3101.4
150267    3096.8
150268    3096.8
Name: Targetted Condition No. 1, Length: 150269, dtype: float64

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05)

# linear regression

In [5]:
lr_model = LinearRegression()
lr_model.fit(x_train.values,y_train.values)


LinearRegression()

In [6]:
lr_predictions=lr_model.predict(x_test.values)
lr_predictions
# predictions.reshape(-1, 1)
# lr_model.score(y_test, predictions)

array([3113.62672809, 3095.64692199, 3106.65576045, ..., 3102.36001774,
       3105.90182044, 3101.54346818])

In [7]:
# y_test

In [8]:
# y_test = y_test.to_numpy()
# y_test.reshape(-1, 1)
y_test

140547    3114.4
70672     3090.8
127360    3102.0
146297    3115.4
88587     3092.6
           ...  
116797    3119.6
66456     3088.4
109487    3105.7
95225     3109.4
23101     3096.7
Name: Targetted Condition No. 1, Length: 7514, dtype: float64

In [9]:
y_test.reshape(-1, 1)
# predictions.reshape(-1, 1)

AttributeError: 'Series' object has no attribute 'reshape'

In [10]:
r2_score(y_test, lr_predictions)

0.7330258991964764

In [11]:
# lr_model.score(y_test, predictions)

# random forest regression

In [12]:
rfr_model = RandomForestRegressor()
rfr_model.fit(x_train.values,y_train.values)

RandomForestRegressor()

In [13]:
rfr_predictions=rfr_model.predict(x_test.values)
rfr_predictions

array([3117.3  , 3103.398, 3096.631, ..., 3099.737, 3103.401, 3109.639])

In [14]:
r2_score(y_test, rfr_predictions)

0.7936261824859429

# GradientBoostingRegressor

In [16]:
rfr_model = GradientBoostingRegressor()
rfr_model.fit(x_train.values,y_train.values)

GradientBoostingRegressor()

In [17]:
rfr_predictions=rfr_model.predict(x_test.values)
rfr_predictions

array([3110.67429215, 3104.41473526, 3097.45989356, ..., 3098.4616152 ,
       3102.18127709, 3109.17852986])

In [18]:
r2_score(y_test, rfr_predictions)

0.7113608072270157

# ExtraTreesRegressor

In [31]:
etr_model = ExtraTreesRegressor()
etr_model.fit(x_train.values,y_train.values)

ExtraTreesRegressor()

In [26]:
etr_predictions=etr_model.predict(x_test.values)
etr_predictions

array([3101.464, 3099.7  , 3099.035, 3104.6  , 3096.4  , 3102.6  ,
       3110.664, 3104.728, 3101.5  , 3106.5  , 3102.249, 3098.367,
       3095.1  , 3098.32 , 3104.126, 3107.459, 3097.4  , 3096.1  ,
       3106.46 , 3100.2  , 3099.818, 3100.829, 3098.149, 3094.714,
       3104.7  , 3109.581, 3091.9  , 3103.2  , 3094.123, 3096.316,
       3099.18 , 3093.8  , 3104.235, 3102.709, 3110.6  , 3099.   ,
       3094.8  , 3101.2  , 3093.569, 3100.005, 3111.2  , 3112.294,
       3100.6  , 3101.3  , 3103.512, 3106.97 , 3098.132, 3102.7  ,
       3110.034, 3110.176, 3104.783, 3100.982, 3101.482, 3099.082,
       3091.527, 3098.8  , 3104.949, 3097.82 , 3105.328, 3094.79 ,
       3101.064, 3095.8  , 3095.842, 3108.711, 3093.811, 3102.208,
       3099.1  , 3106.8  , 3096.38 , 3104.9  , 3108.436, 3106.761,
       3107.756, 3107.3  , 3100.187, 3110.636])

In [27]:
r2_score(y_test, etr_predictions)

0.7417687223601369

# ElasticNet

In [34]:
etr_model = ElasticNet()
etr_model.fit(x_train.values,y_train.values)

ElasticNet()

In [35]:
etr_predictions=etr_model.predict(x_test.values)
etr_predictions

array([3106.46412864, 3103.01507035, 3097.22796124, ..., 3098.44847968,
       3102.1682717 , 3109.76447516])

In [36]:
r2_score(y_test, etr_predictions)

0.4686636850865967

# SGDRegressor

In [22]:
sdg_model = SGDRegressor()
sdg_model.fit(x_train.values,y_train.values)

SGDRegressor()

In [23]:
sdg_predictions=sdg_model.predict(x_test.values)
sdg_predictions

array([5.62757756e+15, 5.86891672e+15, 5.90338606e+15, ...,
       5.89113585e+15, 5.81119431e+15, 5.81714397e+15])

In [24]:
r2_score(y_test, sdg_predictions)

-8.03020717409821e+29

# Support Vector Machine

In [ ]:
svr_model = SVR()
svr_model.fit(x_train.values,y_train.values)

In [40]:
svr_predictions=svr_model.predict(x_test.values)
svr_predictions

array([-5.53386275e+15, -5.49195604e+15, -5.52767810e+15, ...,
       -5.48855957e+15, -5.51501443e+15, -5.52035886e+15])

In [41]:
r2_score(y_test, svr_predictions)

-7.144797507122021e+29

# BayesianRidge

In [25]:
byr_model = BayesianRidge()
byr_model.fit(x_train.values,y_train.values)

BayesianRidge()

In [26]:
byr_predictions=byr_model.predict(x_test.values)
byr_predictions

array([3096.88315959, 3106.64407841, 3108.74492095, ..., 3098.72820749,
       3103.24613923, 3107.07578977])

In [27]:
r2_score(y_test, byr_predictions)

0.7373825218575596

# CatBoostRegressor

In [ ]:
cbr_model = CatBoostRegressor()
cbr_model.fit(x_train.values,y_train.values)

In [40]:
cbr_predictions=cbr_model.predict(x_test.values)
cbr_predictions

array([-5.53386275e+15, -5.49195604e+15, -5.52767810e+15, ...,
       -5.48855957e+15, -5.51501443e+15, -5.52035886e+15])

In [41]:
r2_score(y_test, cbr_predictions)

-7.144797507122021e+29

# KernelRidge

In [28]:
kr_model = KernelRidge()
kr_model.fit(x_train.values,y_train.values)

MemoryError: Unable to allocate 108. GiB for an array with shape (120215, 120215) and data type float64

In [29]:
kr_predictions=kr_model.predict(x_test.values)
kr_predictions

AttributeError: 'KernelRidge' object has no attribute 'X_fit_'

In [41]:
r2_score(y_test, kr_predictions)

-7.144797507122021e+29

# XGBRegressor

In [30]:
xgb_model = KernelRidge()
xgb_model.fit(x_train.values,y_train.values)

MemoryError: Unable to allocate 108. GiB for an array with shape (120215, 120215) and data type float64

In [40]:
xgb_predictions=xgb_model.predict(x_test.values)
xgb_predictions

array([-5.53386275e+15, -5.49195604e+15, -5.52767810e+15, ...,
       -5.48855957e+15, -5.51501443e+15, -5.52035886e+15])

In [41]:
r2_score(y_test, xgb_predictions)

-7.144797507122021e+29

# LGBMRegressor

In [31]:
lgbm_model = KernelRidge()
lgbm_model.fit(x_train.values,y_train.values)

MemoryError: Unable to allocate 108. GiB for an array with shape (120215, 120215) and data type float64

In [32]:
lgbm_predictions=lgbm_model.predict(x_test.values)
lgbm_predictions

AttributeError: 'KernelRidge' object has no attribute 'X_fit_'

In [41]:
r2_score(y_test, lgbm_predictions)

-7.144797507122021e+29

# Evaluation data

In [4]:
all_data=pandas.read_csv("Training Dataset.csv")
all_data

Condition No. 1  Condition No. 2  Condition No. 3  Condition No. 4  \
0                3687.5           4510.6           9.3160           26.734   
1                3685.5           4511.5           9.3103           26.661   
2                3682.8           4570.5           9.2759           26.653   
3                3573.8           4547.2           9.3265           26.517   
4                3644.3           4530.7           9.3318           27.119   
...                 ...              ...              ...              ...   
150264           3602.0           4488.5           9.2903           26.737   
150265           3658.9           4541.8           9.4212           26.887   
150266           3664.7           4481.6           9.3381           27.136   
150267           3716.2           4502.5           9.4016           26.967   
150268           3716.2           4502.5           9.4016           26.967   

        Condition No. 5  Condition No. 6  Condition No. 7  Condition No. 8  \
0                42.511           74.935           120.42          0.33407   
1                42.478           75.888           120.41          0.32859   
2                42.224           75.779           120.43          0.35016   
3                42.246           74.906           120.38          0.33413   
4                42.199           75.036           120.42          0.34601   
...                 ...              ...              ...              ...   
150264           42.304           74.364           120.39          0.33959   
150265           42.675           76.042           120.42          0.34050   
150266           41.835           74.236           120.42          0.31717   
150267           41.867           74.662           120.43          0.34990   
150268           41.867           74.662           120.43          0.34990   

        Condition No. 9  Condition No. 10  ...  Condition No. 25  \
0                80.345            24.203  ...            4.9187   
1                79.935            26.669  ...            4.7347   
2                80.379            23.216  ...            4.8275   
3                80.407            25.154  ...            4.8399   
4                80.233            24.941  ...            4.8477   
...                 ...               ...  ...               ...   
150264           80.119            25.181  ...            4.8674   
150265           79.780            23.205  ...            4.8172   
150266           80.462            23.216  ...            4.8518   
150267           80.211            25.184  ...            4.7766   
150268           80.211            25.184  ...            4.7766   

        Condition No. 26  Condition No. 27  Condition No. 28  \
0                 2.3120          0.018975           0.84982   
1                 2.2965          0.021290           0.85223   
2                 2.2578          0.015472           0.81907   
3                 2.3040          0.007096           0.84621   
4                 2.2572          0.023564           0.83298   
...                  ...               ...               ...   
150264            2.3276          0.010042           0.88338   
150265            2.2964          0.038459           0.81802   
150266            2.2640         -0.002473           0.82219   
150267            2.3251          0.018484           0.81109   
150268            2.3251          0.018484           0.81109   

        Condition No. 29  Condition No. 37  Condition No. 35  \
0               0.107870            53.729            43.107   
1               0.119180            54.179            45.041   
2               0.098032            54.413            42.933   
3               0.101700            53.603            44.186   
4               0.097448            52.915            43.488   
...                  ...               ...               ...   
150264          0.095266            53.332            43.710   
150265          0.087961            

In [5]:
x=all_data.drop(columns=['Targetted Condition No. 1'])
y=all_data['Targetted Condition No. 1']
y

0         3098.8
1         3113.9
2         3100.0
3         3102.7
4         3107.4
           ...  
150264    3108.0
150265    3116.9
150266    3101.4
150267    3096.8
150268    3096.8
Name: Targetted Condition No. 1, Length: 150269, dtype: float64

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05)

# evaluation 

In [14]:
evaluation_data=pandas.read_csv("Evaluation Dataset.csv")
evaluation_data

Condition No. 1  Condition No. 2  Condition No. 3  Condition No. 4  \
0                3633.0           4491.6           9.3233           27.020   
1                3654.7           4526.4           9.2720           26.838   
2                3655.9           4468.3           9.3669           26.702   
3                3689.9           4532.0           9.4211           26.918   
4                3687.9           4494.1           9.5047           26.565   
...                 ...              ...              ...              ...   
239995           3656.9           4518.7           9.4022           27.070   
239996           3695.0           4444.9           9.3209           27.041   
239997           3703.0           4569.6           9.3275           27.103   
239998           3658.7           4555.6           9.4720           27.396   
239999           3607.5           4507.0           9.3117           26.991   

        Condition No. 5  Condition No. 6  Condition No. 7  Condition No. 8  \
0                42.401           74.366           120.42          0.34398   
1                42.280           75.423           120.40          0.34092   
2                41.850           75.461           120.40          0.36692   
3                42.311           73.959           120.41          0.34800   
4                42.208           75.249           120.40          0.34721   
...                 ...              ...              ...              ...   
239995           42.162           75.433           120.42          0.31811   
239996           42.506           75.198           120.42          0.32296   
239997           42.391           75.039           120.43          0.34619   
239998           42.545           74.994           120.41          0.33453   
239999           42.461           75.651           120.39          0.32457   

        Condition No. 9  Condition No. 10  ...  Condition No. 24  \
0                80.054            26.191  ...            2.2794   
1                79.798            25.120  ...            2.2798   
2                80.222            23.749  ...            2.2694   
3                80.085            25.954  ...            2.2522   
4                80.130            25.739  ...            2.2967   
...                 ...               ...  ...               ...   
239995           79.724            24.669  ...            2.2303   
239996           80.330            26.955  ...            2.2977   
239997           80.056            24.436  ...            2.2593   
239998           80.047            24.792  ...            2.2492   
239999           80.328            25.310  ...            2.2238   

        Condition No. 25  Condition No. 26  Condition No. 27  \
0                 4.8459            2.3389         -0.002351   
1                 4.8528            2.2791          0.003044   
2                 4.7115            2.2466          0.024026   
3                 4.8880            2.3085          0.027168   
4                 4.9020            2.2538          0.016510   
...                  ...               ...               ...   
239995            4.6296            2.3208          0.006675   
239996            4.9157            2.2714          0.026402   
239997            4.7596            2.3007          0.026916   
239998            4.7565            2.3150         -0.004883   
239999            4.8310            2.2789          0.022487   

        Condition No. 28  Condition No. 29  Condition No. 37  \
0                0.85592          0.092412            53.696   
1                0.83471          0.117330            54.647   
2                0.81435          0.099781            53.348   
3                0.83669          0.092316            53.861   
4                0.80269          0.101690            53.474   
...                  ...               ...               ...   
239995           0.84120          0.113470            53.057   
239996           0.84725          0.

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.0000001)

In [32]:
y_predict=etr_model.predict(evaluation_data)


C:\Anaconda\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but ExtraTreesRegressor was fitted without feature names
  warnings.warn(


In [33]:
pandas.DataFrame(y_predict).to_csv('esr_all_data_final.csv')